add Obtainium and 2FAS
offa/android-foss pull request #300
Opened 2023-08-11 12:39 UTC by htetoh

2023-08-11 17:35 UTC, offa requested changes
Thanks for your contribution. 2FAS seems to include proprietary components, as far as I can tell.

2023-08-11 17:35 UTC, offa commented on README.md
> +* [**2FAS**](https://github.com/twofas/2fas-android)
The app includes proprietary google services.

2023-08-11 17:36 UTC, offa commented on README.md
> +* [**Obtainium**](https://github.com/ImranR98/Obtainium)
Could fit under *App Store* too? :-)

2023-08-12 08:17 UTC, htetoh reviewed
Done.

2023-08-14 18:54 UTC, offa commented
Perfect, thank you! :-)

2023-08-14 18:54 UTC, offa approved these changes

2023-08-14 18:55 UTC, merged